version: "3.3"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port ${APP_PORT}
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8000:${APP_PORT}"
networks:
  default:
